[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe0b29d6e78e87fb8e0dc993ed40caf64f5a0b4a"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "151e858b0882e0c828fc09077e85644c91c1c0fd02d727f89b184d56a988116e"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b92f020c558730ce81dc94d8d5b921f0597858e0"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "ed64dcbaf1bf25bd2977ced2ab54cc77d4daf03887d176efb71e9453485aa5e6"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea2650050ae4fc13d67f1944a9dc79d494db6934"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "0ec893bfd248782f2d67ffbc1a1ffb791f5124dba9ad3dce877fe18f6e164226"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e0f3d27284c108db55099de8da65b0e194b9113"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "1148a36fb85664e3e7d70e4571574b27a09e9bf421f1d0c3796c8479c2fddcfe"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afc12d777ee84d6b554d7074c5410d409aed770f"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "92524dbcec20a7798062cbdca6a0ba0852f77cbb0e359d7721e8b969aa837973"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8feb76cf6599f92f9bfb81a4dc95cbda6a84f4b9"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "827ab697232713f1c50667cc79acd2de1598ccd39fa9f4d373519f4f34495d8c"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "224ed709862165e66c18fbbd847a10d6632a6d78"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "871d2c3a1abe4948194363bf56e4cf4dcd8ee43ee1798547a1029428f83f73a3"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0955e8c9f540954c02bcebcc23ee9b9194981667"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "1fc53847de4ad7fabf3093b6aaa36451165562de23f76f3ac88eca45496095dd"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.1.0+0/libjlnode.v16.1.0.x86_64-linux-musl-cxx11.tar.gz"
