[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a28073c76d8b638caa527af071bc5604b54d3985"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "7815f670c828e3a9060dd8650bfc79499239a0d249c34015d540230656cf7545"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13d8082f2dea64d31049653718d4ca70c555bfbc"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "3dcbeb04279a8b519728d0dfa8be3f02f594d342f856283a3e683f84a8a987f5"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f3d6c8855b4711f44c449df65d89fab03ecac52"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "52e9e728a470345de9195f16946cc7135f761f4ba960ded06b6eb8c09c327093"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.aarch64-linux-musl-cxx03.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebd130f9c81c70e4b25464b7c093f13ca3895dd9"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "c0830317807f72aa7a17357a2229ed909cb8f719cb1e2ecc7f1b2cacf84b6e28"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.aarch64-linux-musl-cxx11.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dee9d77e1edae57aa573cfc9c8963233f92ee6ce"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "a24a6ea37d9a74411c874632bceb4d97f0459b3b13d71b3c68437a4aac15baab"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cc0570eabc77714f75522aac36f11427885c4a7"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "03243df877ffcfc6e8c4a6020a184c7c10a9a9251f694b7f252acaf97f82e2f0"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf442baac2166b47f0f4ea435b9bb71181abda7b"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "b343c26b1d8c5fdabbd57cef980459147c200c36a7ebf72be6b319b1b35a8ddd"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.x86_64-linux-musl-cxx03.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2084d614f6ef71f89b6df22f78a70b0fe9b9e1d"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "973d4c8f0eee08440841e336b14891da94ff6ba3cf7216846fb1403dd1657f62"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v14.17.3+1/libjlnode.v14.17.3.x86_64-linux-musl-cxx11.tar.gz"
