[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3beccc7641f66fe70d6c5775727bafa761647870"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "75a7d131655478ef679cfe47d8a0dd5452e2403d94a14c308fdafa1b8249cf11"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25a189777b0426eb7b823e633818a3256c1592ca"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "31b2fed7bf01c0b39e504049f3f715f5fcc0c28d122a86e3fafc09145fcb9568"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9bccb7b96d0ff9c5bd62c8dd02b59d2f8e054c3"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "3a2e43dbae95cf4cfb2b19d332b01f319b486db6b8f97d4490be527ec647750c"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[libjlnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8354365801f8d74d1c55c7659d80fcee6378e1ee"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "b3ad910f6205f8f8db92e962d7f72063ce770bbd2dd2b1172cc70ecd25cbfc00"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87b27703e1e452d00ad54d5e5334f0d16a54597a"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "61b44fe1298a4d7cc4d79b2960b536303ff1d8aaed4424b460a9a3f7f21bb636"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4a52e47d47b10b1eed44736ab5efb1650843b09"
libc = "glibc"
os = "linux"

    [[libjlnode.download]]
    sha256 = "5b208f870924d67449eaf3fe4dc75a50c61c9ce250faeda3e1236c0bc8097ac5"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7e78b6c079cafad1a0f707000d0afc327276e94"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "32382ad43378617c5300693b289ec35ca228c3fe8fe374b4520d2c14d70d0b43"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[libjlnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "677b1530e9be80b97a9a831bd08ee33008f8b250"
libc = "musl"
os = "linux"

    [[libjlnode.download]]
    sha256 = "2a40d4ed5f06f2262c09d6f1cac519ea3fd530896e5051e7511064105565ada4"
    url = "https://github.com/JuliaBinaryWrappers/libjlnode_jll.jl/releases/download/libjlnode-v16.0.0+0/libjlnode.v16.0.0.x86_64-linux-musl-cxx11.tar.gz"
